arena_humansim:
  ros__parameters:
    seed: 0
    dt: 0.05
    bt_tick_interval: 5
    perception: default
    global_planner: astar
    local_planner: sfm
    animation: noop
    collision: wall_projection
