name: robot
desired_velocity: 1.1
agent_radius: 0.3
max_velocity: 1.1
max_acceleration: 1.5
max_deceleration: 2.0
min_turning_radius: 0.0
pivot_angular_velocity: 2.0

idle_gaze_rate: 0.0

perception:
  vision_range: 6.0
  vision_fov: 360.0
