<?xml version='1.0' encoding='utf-8'?>
<package format="3">
  <name>arena_humansim_viz</name>
  <version>0.0.0</version>
  <description>Converts arena_humansim AgentViz messages into rviz marker arrays</description>
  <maintainer email="dev@voshch.dev">voshch</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>visualization_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>std_msgs</depend>
  <depend>arena_humansim_msgs</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
